# default config
baseURL = "https://www.remoteworklibrary.io/"
languageCode = "en-us"
title = "Remote Work Library"
theme = "parsa-hugo"
summaryLength = "10"
paginate = 100

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# navigation
[[menu.main]]
name = "About"
URL = "about"
weight = 2

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 3

# site parameter
[params]
logo = "logo.png"
home = "Home"

# theme layout ( two layout is available, "1" and "2" )
layout = "1"

# Meta data
description = "an open library of remote work culture, practices and tools"

# Preloader
preloader = true

# search
search = true

# Contact info
company = "QAware GmbH"
tel = "+49 89 232315-0"
email = "info@qaware.de"
street = "Aschauer Str. 32"
city = "81549 Munich, Germany"

# Contact Form Action
contact_form_action = "#"
# Google Analitycs
google_analitycs_id = "UA-538827-4"
# copyright
copyright = "made with ‚ù§ from home"

socialShareLinkedin  = true
socialLinkedAccount = "qaware-gmbh"
socialShareTwitter = true
socialTwitterAccount = "qaware"

# Instagram feed
[params.instafeed]
enable = false
user_id = "4044026246"
access_token = "4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"

# social site

[[params.social]]
icon = "ti-twitter-alt"
URL = "https://twitter.com/qaware"

[[params.social]]
icon = "ti-linkedin"
URL = "https://www.linkedin.com/company/qaware-gmbh"

[[params.social]]
icon = "ti-github"
URL = "https://github.com/remoteworklibrary"